const crypto=require('node:crypto');const zlib=require('node:zlib');
const RESOLVE='https://api.takeads.com/v1/product/monetize-api/v2/resolve';const MERCHANT='https://api.takeads.com/v1/product/monetize-api/v2/merchant';
const SECRET='ccgo_v1_1_0_8e4bc3c6e535aaf0d3d95a5bd8971e3297f41aa1d2a14f17607b66c48adf79ae';
const STORES={mercadolivre:['mercadolivre.com.br','mercadolivre.com','mercadolibre.com'],shopee:['shopee.com.br'],amazon:['amazon.com.br'],aliexpress:['aliexpress.com'],magalu:['magazineluiza.com.br'],shein:['shein.com'],netshoes:['netshoes.com.br'],casasbahia:['casasbahia.com.br'],kabum:['kabum.com.br'],centauro:['centauro.com.br'],sephora:['sephora.com.br'],epoca:['epocacosmeticos.com.br'],belezanaweb:['belezanaweb.com.br'],ponto:['pontofrio.com.br','ponto.com.br'],fastshop:['fastshop.com.br'],carrefour:['carrefour.com.br'],americanas:['americanas.com.br'],extra:['extra.com.br']};
const ALIAS={'mercado-livre':'mercadolivre','mercado_livre':'mercadolivre',magazine_luiza:'magalu',magazineluiza:'magalu','casas-bahia':'casasbahia',beleza_na_web:'belezanaweb'};
const sid=v=>ALIAS[String(v||'').trim().toLowerCase()]||String(v||'').trim().toLowerCase();
function hm(h,a){h=String(h||'').toLowerCase().replace(/^www\./,'');return a.some(b=>h===b||h.endsWith('.'+b))}
function detect(raw){let u;try{u=new URL(raw)}catch{return''}for(const [id,hs]of Object.entries(STORES))if(hm(u.hostname,hs))return id;return''}
function norm(raw,hint=''){let u;try{u=new URL(String(raw||''))}catch{throw Error('URL inválida.')}if(u.protocol!=='https:'||u.username||u.password)throw Error('URL não permitida.');const d=detect(u.toString());if(!d)throw Error('Loja não autorizada.');const h=sid(hint);if(h&&STORES[h]&&h!==d)throw Error('Loja não corresponde ao link.');for(const k of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','fbclid'])u.searchParams.delete(k);u.hash='';return{url:u.toString(),store:d}}
function key(){return String(process.env.TAKEADS_PLATFORM_PUBLIC_KEY||'').trim()}
function sign(x){return crypto.createHmac('sha256',String(process.env.REDIRECT_SIGNING_SECRET||SECRET)).update(x).digest('base64url')}
function token(o){const n=norm(o.url,o.store),now=Math.floor(Date.now()/1000),x=zlib.deflateRawSync(Buffer.from(JSON.stringify({v:2,u:n.url,s:n.store,iat:now,exp:now+2592000}))).toString('base64url');return x+'.'+sign(x)}
function untoken(raw){const p=String(raw||'').split('.');let x;if(p.length===1){x=JSON.parse(zlib.inflateRawSync(Buffer.from(p[0],'base64url')).toString('utf8'));if(!x||x.v!==1)throw Error('Token inválido.')}else{if(p.length!==2||sign(p[0])!==p[1])throw Error('Assinatura inválida.');x=JSON.parse(zlib.inflateRawSync(Buffer.from(p[0],'base64url')).toString('utf8'));if(!x||x.v!==2||x.exp<Math.floor(Date.now()/1000))throw Error('Token inválido ou expirado.')}const n=norm(x.u,x.s);return{u:n.url,s:n.store}}
function sub(store){const p=String(process.env.TAKEADS_SUBID_PREFIX||'cc_ext').replace(/[^A-Za-z0-9_-]/g,'').slice(0,48)||'cc_ext';return(p+'_'+String(store||'store').replace(/[^A-Za-z0-9_-]/g,'').slice(0,32)).slice(0,96)}
function cors(req,res){const o=String(req.headers.origin||'');if(!o||o.startsWith('chrome-extension://'))res.setHeader('Access-Control-Allow-Origin',o||'*');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store')}
async function affiliate(url,store){const n=norm(url,store);if(!key())return{destination:n.url,monetized:false,provider:'passthrough',reason:'not_configured'};try{const r=await fetch(RESOLVE,{method:'PUT',headers:{Authorization:'Bearer '+key(),'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({iris:[n.url],subId:sub(n.store),withImages:false}),signal:AbortSignal.timeout(Math.max(500,Math.min(5000,Number(process.env.TAKEADS_TIMEOUT_MS||2200))))});const t=await r.text();let b={};try{b=JSON.parse(t)}catch{}if(!r.ok)return{destination:n.url,monetized:false,provider:'passthrough',reason:'takeads_http_'+r.status,status:r.status,error:b?.errors||t.slice(0,300)};const it=Array.isArray(b.data)?b.data[0]:null;if(!it?.trackingLink)return{destination:n.url,monetized:false,provider:'passthrough',reason:'merchant_not_found'};return{destination:it.trackingLink,monetized:true,provider:'takeads',reason:'ok'}}catch(e){return{destination:n.url,monetized:false,provider:'passthrough',reason:'takeads_network_error',error:String(e?.message||e)}}}
function json(res,s,b){res.setHeader('Content-Type','application/json; charset=utf-8');res.status(s).json(b)}
function html(res,title,body){res.setHeader('Content-Type','text/html; charset=utf-8');res.status(200).send(`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font:16px/1.6 system-ui;max-width:850px;margin:40px auto;padding:0 22px;color:#10294d}h1,h2{color:#062b5b}</style>${body}`)}
async function merchants(res){if(!key())return json(res,503,{ok:false,takeadsConfigured:false,error:'Takeads não configurada.'});try{const u=new URL(MERCHANT);u.searchParams.set('limit','500');u.searchParams.set('isActive','true');u.searchParams.set('deeplinkAllowed','true');const r=await fetch(u,{headers:{Authorization:'Bearer '+key(),Accept:'application/json','Content-Type':'application/json'},signal:AbortSignal.timeout(6000)});const t=await r.text();let b={};try{b=JSON.parse(t)}catch{}if(!r.ok)return json(res,502,{ok:false,takeadsConfigured:true,http:r.status,error:b?.errors||t.slice(0,500)});const ms=Array.isArray(b.data)?b.data:[];const cv=Object.entries(STORES).map(([store,hosts])=>{const matches=ms.filter(m=>[m?.defaultDomain,...(Array.isArray(m?.domains)?m.domains:[])].filter(Boolean).some(d=>hosts.some(h=>{d=String(d).toLowerCase().replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];return d===h||d.endsWith('.'+h)||h.endsWith('.'+d)})));const m=matches[0];return{store,supported:matches.length>0,merchantCount:matches.length,merchant:m?{merchantId:m.merchantId,name:m.name,defaultDomain:m.defaultDomain,averageCommission:m.averageCommission,commissionRates:m.commissionRates,paymentModels:m.paymentModels,countryCodes:m.countryCodes,deeplinkAllowed:m.deeplinkAllowed,isActive:m.isActive}:null}});return json(res,200,{ok:true,takeadsConfigured:true,merchantsScanned:ms.length,next:b?.meta?.next??null,coverage:cv})}catch(e){return json(res,502,{ok:false,takeadsConfigured:true,error:String(e?.message||e)})}}
module.exports=async function(req,res){const p=String(req.url||'').split('?')[0];res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');
if(p==='/health'){const kh=key()?crypto.createHash('sha256').update(key()).digest('hex').slice(0,12):null;return json(res,200,{ok:true,service:'cacador-cupons-go',version:'1.2.1',affiliateMode:key()?'takeads-on-click':'passthrough-ready',takeadsConfigured:!!key(),takeadsKeyHash:kh});}
if(p==='/merchants')return merchants(res);
if(p==='/api/resolve'){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return json(res,405,{ok:false,error:'Método não permitido.'});try{const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{}),n=norm(b.url,b.store),tk=token(n),proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0],host=String(req.headers['x-forwarded-host']||req.headers.host).split(',')[0];return json(res,200,{ok:true,url:`${proto}://${host}/r/${tk}`,originalUrl:n.url,store:n.store,monetized:false,provider:key()?'takeads-on-click':'passthrough'})}catch(e){return json(res,400,{ok:false,error:String(e?.message||e)})}}
if(p.startsWith('/r/')){try{const x=untoken(decodeURIComponent(p.slice(3))),a=await affiliate(x.u,x.s);console.log(JSON.stringify({event:'affiliate_click',store:x.s,provider:a.provider,monetized:a.monetized,reason:a.reason,at:new Date().toISOString()}));return res.redirect(302,a.destination||x.u)}catch(e){return json(res,400,{ok:false,error:'Link inválido, expirado ou não autorizado.'})}}
if(p==='/privacy')return html(res,'Política de Privacidade — Caçador de Cupons','<h1>Política de Privacidade — Caçador de Cupons</h1><p>A extensão processa informações de páginas de produtos, cupons, preços e URLs necessárias às funções de comparação, monitoramento e abertura de ofertas. Ao abrir determinadas ofertas, a URL e a identificação da loja podem ser enviadas ao serviço do Caçador de Cupons para validação e, quando habilitado, conversão em link de afiliado pela Takeads/Mitgo. Não vendemos dados pessoais nem solicitamos dados de pagamento.</p>');
if(p==='/support')return html(res,'Suporte — Caçador de Cupons','<h1>Suporte — Caçador de Cupons</h1><p>Use o canal informado na página da extensão na Chrome Web Store para suporte. Não envie senhas ou dados de pagamento.</p>');
if(p==='/')return html(res,'Caçador de Cupons','<h1>Caçador de Cupons</h1><p>Serviço de apoio da extensão para cupons, comparação de preços e ofertas.</p><p><a href="/privacy">Política de Privacidade</a> · <a href="/support">Suporte</a></p>');
return json(res,404,{ok:false,error:'Not found'});
}
